---
swagger: "2.0"
info:
  description: "Kubernetes image policy webhook service for anchore-engine"
  version: "0.9.0"
  title: "Kubernetes Image Policy Webhook"
  contact:
    email: "dev@anchore.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
#host: "localhost:83"
basePath: "/"
tags:
- name: "kubernetes_webhook"
  description: "Kubernetes Image Policy Webhook"
  externalDocs:
    description: "Find out more"
    url: "http://anchore.com"
schemes:
- "https"
- "http"

securityDefinitions:
  basicAuth:
    type: basic

security:
  - basicAuth: []

paths:
  /status:
    get:
      tags:
      - "kubernetes_webhook"
      summary: "Get the status of the service"
      description: ""
      operationId: "status"
      x-anchore-authz-action: None
      produces:
      - "application/json"
      responses:
        200:
          description: "service status"
          schema:
            type: object
      x-swagger-router-controller: "anchore_engine.services.kubernetes_webhook.api.controllers.default_controller"
  /imagepolicywebhook:
    post:
      tags:
      - "kubernetes_webhook"
      summary: "Kubernetes image policy webhook service call"
      description: ""
      operationId: "imagepolicywebhook"
      x-anchore-authz-action: getImageEvaluation
      parameters:
      - name: 'bodycontent'
        in: body
        schema:
          type: object
        description: "object from kubernetes to check in anchore"
        required: true
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            type: object
      x-swagger-router-controller: "anchore_engine.services.kubernetes_webhook.api.controllers.default_controller"
