# CircleCI 2.1 configuration file
# Check https://circleci.com/docs/2.0/configuration-reference/ for more details
#
# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name`
# syntax dereferences it.
#
# Define YAML anchors
.global_environment_vars: &global_environment_vars
  PROD_IMAGE_REPO: anchore/anchore-engine
  LATEST_RELEASE_MAJOR_VERSION: 0.10.0
  TERM: xterm

.attach_workspace: &attach_workspace
  attach_workspace:
    at: /home/circleci/workspace/

.load_docker_image: &load_docker_image
  run:
    name: Load Docker image layer cache
    command: |
      docker load -i "/home/circleci/workspace/caches/${CIRCLE_SHA1}.tar" || true

.ssh_forward_port: &ssh_forward_port
  run:
    name: Forward remote-docker ports for testing
    command: |
      ssh -MS anchore-api -fN4 -L 8228:localhost:8228 remote-docker
      ssh -MS k8s-api -fN4 -L 32768:localhost:32768 remote-docker

.filter_rc_tags: &filter_rc_tags
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+(\.[0-9]+)*-rc[0-9]+$/

.filter_rebuild_tags: &filter_rebuild_tags
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+(\.[0-9]+)*-r[0-9]+$/

.filter_release_branch: &filter_release_branch
  branches:
    only:
      - /^[0-9]+(\.[0-9]+)$/
      - master
      - /^ci-.*/
      - /^v[0-9]+(\.[0-9]+)*-dev$/

.filter_semver_tags: &filter_semver_tags
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+(\.[0-9]+)*$/

.filter_nightly: &filter_nightly
  branches:
    only:
      - master

# Start circleci configuration
version: 2.1
orbs:
  anchore: anchore/anchore-engine@1

commands:
  run_tests:
    description: |
      Uses make script to run tests
      Saves the tox cache & stores log output as artifacts
    parameters:
      test_type:
        type: string
      tox_env:
        type: string
        default: "py38"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          echo 'export TOX_ENV="<< parameters.tox_env >>"' >> $BASH_ENV
      - run:
          name: run tests
          command: |
            make << parameters.test_type >>
      - save_cache:
          paths:
            - ~/project/.tox
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - store_test_results:
          path: .tox/results
      - store_artifacts:
          path: .tox/test-reports.log
          destination: test-reports.log

jobs:
  unit_tests:
    parameters:
      py_version:
        type: string
      tox_env:
        type: string
    docker:
      - image: circleci/python:<<parameters.py_version>>
    environment: *global_environment_vars
    steps:
      - checkout
      - run_tests:
          test_type: test-unit
          tox_env: <<parameters.tox_env>>

  validate_swagger:
    description: |
      Validates the swagger files against the spec
    docker:
      - image: circleci/python:3.8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: run tests
          command: |
            for i in $(find . -name 'swagger.yaml'); do
              set -e
              scp $i remote-docker:swagger.yaml
              docker run --rm -v ${HOME}:/local openapitools/openapi-generator-cli:v4.1.3 validate -i /local/swagger.yaml --recommend
            done

  lint:
    parameters:
      py_version:
        type: string
    docker:
      - image: circleci/python:<<parameters.py_version>>
    environment: *global_environment_vars
    steps:
      - checkout
      - run_tests:
          test_type: lint

  integration_tests:
    parameters:
      py_version:
        type: string
      tox_env:
        type: string
    docker:
      - image: circleci/python:<<parameters.py_version>>
      - image: anchore/test-infra-minio:latest
        command:
          - server
          - /data
      - image: anchore/test-infra-swift:latest
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_PASSWORD: "postgres"
    resource_class: large
    environment:
      <<: *global_environment_vars
      ANCHORE_TEST_S3_ACCESS_KEY: "9EB92C7W61YPFQ6QLDOU"
      ANCHORE_TEST_S3_SECRET_KEY: "TuHo2UbBx+amD3YiCeidy+R3q82MPTPiyd+dlW+s"
      ANCHORE_TEST_S3_URL: "http://localhost:9000"
      ANCHORE_TEST_S3_BUCKET: "testarchivebucket"

      ANCHORE_TEST_SWIFT_AUTH_URL: "http://localhost:8080/auth/v1.0"
      ANCHORE_TEST_SWIFT_KEY: "testing"
      ANCHORE_TEST_SWIFT_USER: "test:tester"
      ANCHORE_TEST_SWIFT_CONTAINER: "testarchive"

      ANCHORE_TEST_DB_URL: "postgresql+pg8000://postgres@localhost:5432/circle_test"
      ANCHORE_TEST_DB_USER: "postgres"
      ANCHORE_TEST_DB_PASS: "postgres"
      ANCHORE_TEST_DATA_ENV_DIR: "test/data/test_data_env"
    steps:
      - checkout
      - run_tests:
          test_type: test-integration
          tox_env: <<parameters.tox_env>>

  build:
    docker:
      - image: circleci/python:3.8
    resource_class: large
    environment: *global_environment_vars
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: make build
      - run:
          name: Save image to workspace
          command: |
            rm -rf /home/circleci/workspace/caches/
            mkdir -p /home/circleci/workspace/caches/
            docker save -o "/home/circleci/workspace/caches/${CIRCLE_SHA1}.tar" ${CIRCLE_PROJECT_REPONAME}:dev
      - persist_to_workspace:
          root: /home/circleci/workspace/
          paths:
            - caches/*

  functional_tests:
    parameters:
      tox_env:
        type: string
      vulnerabilities_provider:
        type: string
        default: "-grype"

    machine:
      image: ubuntu-1604:202007-01
    environment:
      <<: *global_environment_vars
      ANCHORE_TEST_DOCKER_REGISTRY_USER: anchore
      ANCHORE_TEST_DOCKER_REGISTRY_PASS: foobar
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *load_docker_image
      - run: |
          echo 'export TOX_ENV="<< parameters.tox_env >>"' >> $BASH_ENV
      - run:
          name: Run functional tests
          command: make setup-and-test-functional-<< parameters.vulnerabilities_provider >>

  e2e_tests:
    parameters:
      py_version:
        type: string
    docker:
      - image: circleci/python:<<parameters.py_version>>
    resource_class: large
    environment: *global_environment_vars
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - <<: *load_docker_image
      - <<: *ssh_forward_port
      - run:
          name: Run e2e tests
          no_output_timeout: 30m
          command: make setup-and-test-e2e

  push_image:
    description: Uses make script to push images to DockerHub - dev, rc, prod
    parameters:
      make_job:
        type: string
    docker:
      - image: circleci/python:3.8
    environment: *global_environment_vars
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - <<: *load_docker_image
      - run:
          name: Push to Dockerhub
          command: make << parameters.make_job >>

  container_tests:
    description: Check container properties
    parameters:
      # dev:  a docker build job *must* take place before the job so that
      #       there is a local image for it to run
      # prod: the script that this invokes pulls the image from dockerhub
      test_env:
        type: enum
        default: "dev"
        enum: ["dev", "prod"]
    docker:
      - image: circleci/python:3.8
    environment: *global_environment_vars
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace
      - <<: *load_docker_image
      - run:
          name: Run container-structure-tests
          command: make test-container-<< parameters.test_env >>

workflows:
  default_workflow:
    jobs:
      - unit_tests:
          name: unit_tests_38
          py_version: "3.8"
          tox_env: "py38"
      - lint:
          name: lint_38
          py_version: "3.8"
      - validate_swagger
      - integration_tests:
          name: integration_tests_38
          py_version: "3.8"
          tox_env: "py38"
          requires:
            - unit_tests_38
      - build:
          requires:
            - unit_tests_38
      - container_tests:
          name: test_container_dev
          test_env: "dev"
          requires:
            - build
      - functional_tests:
          name: functional_tests_38_legacy
          tox_env: "py38"
          vulnerabilities_provider: "legacy"
          requires:
            - build
      - functional_tests:
          name: functional_tests_38_grype
          vulnerabilities_provider: "grype"
          tox_env: "py38"
          requires:
            - build
      - push_image:
          name: push_dev_image
          make_job: push-dev
          context: dockerhub
          filters: *filter_release_branch
          requires:
            - functional_tests_38_grype
            - functional_tests_38_legacy
            - integration_tests_38
            - test_container_dev
      - anchore/image_scan:
          context: dockerhub
          requires:
            - push_dev_image
          image_name: anchore/anchore-engine-dev:${CIRCLE_SHA1}
          private_registry: true
          timeout: "2000"

  nightly_build:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - unit_tests:
          name: unit_tests_38
          py_version: "3.8"
          tox_env: "py38"
          filters: *filter_nightly
      - lint:
          name: lint_38
          py_version: "3.8"
          filters: *filter_nightly
      - integration_tests:
          name: integration_tests_38
          py_version: "3.8"
          tox_env: "py38"
          filters: *filter_nightly
          requires:
            - unit_tests_38
      - build:
          filters: *filter_nightly
          requires:
            - unit_tests_38
      - container_tests:
          name: test_container_nightly
          test_env: "dev"
          filters: *filter_nightly
          requires:
            - build
      - functional_tests:
          name: functional_tests_38_legacy
          vulnerabilities_provider: "legacy"
          tox_env: "py38"
          filters: *filter_nightly
          requires:
            - build
      - functional_tests:
          name: functional_tests_38_grype
          vulnerabilities_provider: "grype"
          tox_env: "py38"
          filters: *filter_nightly
          requires:
            - build
      - e2e_tests:
          name: e2e_tests_38
          py_version: "3.8"
          context: e2e-testing
          filters: *filter_nightly
          requires:
            - build
      - push_image:
          name: push_nightly_image
          make_job: push-nightly
          context: dockerhub
          filters: *filter_nightly
          requires:
            - functional_tests_38_legacy
            - functional_tests_38_grype
            - integration_tests_38
            - e2e_tests_38
            - test_container_nightly
      - anchore/image_scan:
          context: dockerhub
          filters: *filter_nightly
          requires:
            - push_nightly_image
          image_name: anchore/anchore-engine-dev:nightly
          private_registry: true
          timeout: "2000"

  rc_image_workflow:
    jobs:
      - build:
          filters: *filter_rc_tags
      - container_tests:
          name: test_container_rc
          test_env: dev
          filters: *filter_rc_tags
          requires:
            - build
      - e2e_tests:
          name: rc_e2e_tests_38
          py_version: "3.8"
          context: e2e-testing
          filters: *filter_rc_tags
          requires:
            - build
      - push_image:
          name: push_rc_image
          make_job: push-rc
          context: dockerhub
          filters: *filter_rc_tags
          requires:
            - rc_e2e_tests_38
            - test_container_rc
      - anchore/image_scan:
          context: dockerhub
          filters: *filter_rc_tags
          requires:
            - push_rc_image
          image_name: anchore/anchore-engine-dev:${CIRCLE_TAG}
          private_registry: true
          timeout: "2000"
          policy_failure: true

  prod_image_workflow:
    jobs:
      - e2e_tests:
          name: prod_e2e_tests_38
          py_version: "3.8"
          context: e2e-testing
          filters: *filter_semver_tags
      - hold_for_approval:
          type: approval
          filters: *filter_semver_tags
          requires:
            - prod_e2e_tests_38
      - push_image:
          name: push_prod_image
          make_job: push-prod
          context: dockerhub-prod
          filters: *filter_semver_tags
          requires:
            - hold_for_approval
      - push_image:
          name: push_redhat_image
          make_job: push-redhat
          context: dockerhub-prod
          filters: *filter_semver_tags
          requires:
            - push_prod_image
      - container_tests:
          name: test_container_prod
          test_env: prod
          context: dockerhub-prod
          filters: *filter_semver_tags
          requires:
            - push_prod_image

  rebuild_image_workflow:
    jobs:
      - unit_tests:
          name: unit_tests_38
          py_version: "3.8"
          tox_env: "py38"
          filters: *filter_rebuild_tags
      - lint:
          name: lint_38
          py_version: "3.8"
          filters: *filter_rebuild_tags
      - integration_tests:
          name: integration_tests_38
          py_version: "3.8"
          tox_env: "py38"
          filters: *filter_rebuild_tags
          requires:
            - unit_tests_38
      - build:
          filters: *filter_rebuild_tags
          requires:
            - unit_tests_38
      - container_tests:
          name: test_container_rebuild
          test_env: dev
          filters: *filter_rebuild_tags
          requires:
            - build
      - functional_tests:
          name: functional_tests_38_legacy
          vulnerabilities_provider: "legacy"
          tox_env: "py38"
          filters: *filter_rebuild_tags
          requires:
            - build
      - functional_tests:
          name: functional_tests_38_grype
          vulnerabilities_provider: "grype"
          tox_env: "py38"
          filters: *filter_rebuild_tags
          requires:
            - build
      - e2e_tests:
          name: e2e_tests_38
          py_version: "3.8"
          context: e2e-testing
          filters: *filter_rebuild_tags
          requires:
            - build
      - push_image:
          name: push_dev_image
          make_job: push-dev
          context: dockerhub
          filters: *filter_rebuild_tags
          requires:
            - e2e_tests_38
            - functional_tests_38_legacy
            - functional_tests_38_grype
            - integration_tests_38
            - test_container_rebuild
      - anchore/image_scan:
          name: anchore_image_scan
          context: dockerhub
          requires:
            - push_dev_image
          image_name: anchore/anchore-engine-dev:${CIRCLE_SHA1}
          private_registry: true
          timeout: "2000"
          policy_failure: true
      - hold_for_approval:
          type: approval
          filters: *filter_rebuild_tags
          requires:
            - anchore_image_scan
      - push_image:
          name: push_rebuild_image
          make_job: push-rebuild
          context: dockerhub-prod
          filters: *filter_rebuild_tags
          requires:
            - hold_for_approval
