#
#  IMPORTANT NOTE - for anchore-engine 0.4.0 and latest, we have moved
#  to a new docker-compose method and approach for deploying
#  anchore-engine with docker-compose, which more accurately reflects
#  production deployment setups.
#
#  Please refer to the latest documentation for running anchore-engine
#  with docker-compose:
#
#  https://docs.anchore.com/2.0/docs/engine/engine_installation/docker_compose/
#
#  The following docker-compose.yaml has been altered to reference the
#  latest 0.3 series release of anchore-engine for continuity, but
#  note that both this and the associated config.yaml in this
#  directory will be removed in the future.
#

version: '2'
services:
  anchore-engine:
    image: docker.io/anchore/anchore-engine:v0.3.4
    #privileged: true
    depends_on:
     - anchore-db
    ports:
     - "8228:8228"
     - "8338:8338"
    volumes:
     - ./config:/config/:z
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    environment:
     # NOTE: this should be set to the same name as this service (e.g. anchore-engine)
     - ANCHORE_HOST_ID=dockerhostid-anchore-engine
     - ANCHORE_ENDPOINT_HOSTNAME=anchore-engine
  anchore-db:
    image: "postgres:9"
    volumes:
     - ./db:/var/lib/postgresql/data/pgdata/:z
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata/
    logging:
     driver: "json-file"
     options:
      max-size: 100m
    #uncomment to expose a port to allow direct/external access to the DB, for debugging
    #ports:
    # - "2345:5432"
#### uncomment this section to enable a prometheus service running alongside anchore-engine for metrics gathering/display
#  anchore-prometheus:
#    image: docker.io/prom/prometheus:latest
#    depends_on:
#     - anchore-engine
#    volumes:
#     - ./anchore-prometheus.yaml:/etc/prometheus/prometheus.yml:z
#    logging:
#     driver: "json-file"
#     options:
#      max-size: 100m
#    ports:
#     - "9090:9090"
