# Anchore analyzer config file
#
# Options for any analyzer module(s) that takes customizable input
#

#
# example configuration for the 'retrieve_files' analyzer, if installed
#

retrieve_files:
  file_list:
    - '/etc/passwd'
#    - '/etc/services'
#    - '/etc/sudoers'


#
# example configuration for the 'content_search' analyze, if installed
#

#content_search:
#  match_params:
#    - MAXFILESIZE=100000
#    - STOREONMATCH=y
#  regexp_match:
#    - ".*password.*"
